Add french support Add Icon Update use of PlayOnLinux calls

diff --git a/outcast-gog b/outcast-gog
--- a/outcast-gog
+++ b/outcast-gog
@@ -12,13 +12,13 @@
 source "$PLAYONLINUX/lib/sources"
 
 abort () {
-    POL_SetupWindow_message_image "An error occurred, the installation is aborted." "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
+    POL_SetupWindow_message_image "$LNG_ABORTED" "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
     POL_SetupWindow_Close
     exit 1
 }
 
 check_install_archive () {
-    POL_SetupWindow_wait_next_signal "Checking install archive..." "$TITLE"
+    POL_SetupWindow_wait_next_signal "$LNG_CHECK_ARCHIVE" "$TITLE"
 
     EXPECTED_SIZE=1409323648
     EXPECTED_MD5="a8bf2336a580527f0eb99f8b90009c33"
@@ -29,51 +29,79 @@ check_install_archive () {
     POL_SetupWindow_detect_exit
 
     if [ $SIZE != $EXPECTED_SIZE -o "$MD5" -ne "$EXPECTED_MD5" ]; then
-	POL_SetupWindow_message_image "Install archive mismatch.\nEither your install archive is corrupted, or is not the expected version.\nThis script cannot guarantee that installation will work correctly. Please report success or failure to PlayOnLinux forums.\n\nSize: $SIZE (expected $EXPECTED_SIZE)\nMD5: $MD5 (expected $EXPECTED_MD5)" "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
+	POL_SetupWindow_message_image "$(printf $LNG_ARCHIVE_MISMATCH $SIZE $EXPECTED_SIZE $MD5 $EXPECTED_MD5)" "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
 	POL_SetupWindow_question "Continue?" "$TITLE"
 	[ "$APP_ANSWER" -ne "TRUE" ] && abort
     fi
 }
 
 
-TITLE="Outcast (GoG release)"
-PREFIX="Outcast-gog"
-SHORTCUT_NAME="Outcast"
+PREFIX="Outcast_gog"
 WORKING_WINE_VERSION="1.3.27-rawinput2"
 
-POL_SetupWindow_Init
-POL_SetupWindow_presentation "Outcast (GoG release)" "Appeal S.A. / Atari" "http://www.gog.com/en/gamecard/outcast" "Pierre Etchemaite" "$PREFIX"
- 
- 
-select_prefix "$DIRECTORY/wineprefix/$PREFIX/"
-POL_SetupWindow_prefixcreate
-cd $HOME
-POL_SetupWindow_browse "Plese select the location of the install file" "Select file"
+case "$POL_LANG" in
+    fr)
+	TITLE="Outcast (version GoG)"
+	SHORTCUT_NAME="Outcast"
+	SHORTCUT_DOC="Manuel de l'utilisateur Outcast"
+	LNG_ABORTED="Une erreur est survenue, l'installation est interrompue."
+	LNG_CHECK_ARCHIVE="Test de l'archive d'installation..."
+	LNG_ARCHIVE_MISMATCH="L'archive ne correspond pas.\nOu bien elle est corrompue, ou ce n'est pas la version attendue.\nCe script ne peut pas garantir que l'installation se passera bien, pensez à communiquer le résultat de l'installation sur le forum de PlayOnLinux.\n\nTaille: %d (attendue %d)\nMD5: %s (attendu %s)"
+	LNG_ARCHIVE_LOCATION="Indiquez l'emplacement de l'archive d'installation"
+	LNG_SELECT_FILE="Sélectionnez le fichier"
+	LNG_INSTALLING="Installation de $SHORTCUT_NAME..."
+	;;
+    *)
+	TITLE="Outcast (GoG release)"
+	SHORTCUT_NAME="Outcast"
+	SHORTCUT_DOC="Outcast user manual"
+	LNG_ABORTED="An error occurred, the installation is aborted."
+	LNG_CHECK_ARCHIVE="Checking install archive..."
+	LNG_ARCHIVE_MISMATCH="Install archive mismatch.\nEither your install archive is corrupted, or is not the expected version.\nThis script cannot guarantee that installation will work correctly. Please report success or failure to PlayOnLinux forums.\n\nSize: %d (expected %d)\nMD5: %s (expected %s)"
+	LNG_ARCHIVE_LOCATION="Please select the location of the install file"
+	LNG_SELECT_FILE="Select file"
+	LNG_INSTALLING="Installing $SHORTCUT_NAME..."
+	;;
+esac
 
-# Doesn't work
-# check_install_archive
+POL_SetupWindow_Init
+POL_SetupWindow_presentation "$TITLE" "Appeal S.A. / Atari" "http://www.gog.com/en/gamecard/outcast" "Pierre Etchemaite" "$PREFIX"
+ 
+ 
+POL_Wine_SelectPrefix "$PREFIX"
+POL_Wine_PrefixCreate
+POL_LoadVar_PROGRAMFILES
+
+cd $HOME
+POL_SetupWindow_browse "$LNG_ARCHIVE_LOCATION" "$LNG_SELECT_FILE"
+
+# Doesn't work?
+#check_install_archive
 
 POL_SetupWindow_install_wine "$WORKING_WINE_VERSION"
-Use_WineVersion "$WORKING_WINE_VERSION"
+export WINEVERSION="$WORKING_WINE_VERSION"
 
 
-POL_SetupWindow_wait_next_signal "Installing Outcast..." "$TITLE"
+POL_SetupWindow_wait_next_signal "$LNG_INSTALLING" "$TITLE"
 
 # Associate .PDF with native app 
 # http://wiki.winehq.org/FAQ#head-91bf3f0a8ccbfab8dee96f82fae2f1a489e0d243
 # Do it before installing the game, so you have the possibility to open
 # PDFs with Win32 reader if you choose to install it
-cat <<'EOF' > $DIRECTORY/tmp/pdfnativereader.reg
+cat <<'EOF' > $REPERTOIRE/tmp/pdfnativereader.reg
 [HKEY_CLASSES_ROOT\.pdf]
 @="PDFfile"
 "Content Type"="application/pdf"
 [HKEY_CLASSES_ROOT\PDFfile\Shell\Open\command]
 @="winebrowser \"%1\""
 EOF
-wine regedit $DIRECTORY/tmp/pdfnativereader.reg
+wine regedit $REPERTOIRE/tmp/pdfnativereader.reg
 
 
 wine "$APP_ANSWER" || abort
+
+# GoG work!
+Set_OS winxp
 
 # Main game will crash if desktop size is not constrained
 Set_Desktop "On" "640" "480"
@@ -85,13 +113,13 @@ Set_Desktop "On" "640" "480"
 
 
 # Set_GrabFullScreen anyone?
-cat <<'EOF' > $DIRECTORY/tmp/grabfullscreen.reg
+cat <<'EOF' > $REPERTOIRE/tmp/grabfullscreen.reg
 REGEDIT4
 
 [HKEY_CURRENT_USER\Software\Wine\X11 Driver]
 "GrabFullscreen"="Y"
 EOF
-wine regedit $DIRECTORY/tmp/grabfullscreen.reg
+wine regedit $REPERTOIRE/tmp/grabfullscreen.reg
 
 POL_SetupWindow_detect_exit
 
@@ -100,22 +128,35 @@ POL_SetupWindow_reboot
 
 
 # Warning, /windows/command/ also contains a start.exe, so
-# POL_SetupWindow_auto_shortcut can fail
-POL_SetupWindow_make_shortcut "$PREFIX" "Program Files/GOG.com/Outcast/" "start.exe" "${SHORTCUT_NAME}.ICO" "$SHORTCUT_NAME"
+# POL_SetupWindow_auto_shortcut or POL_Shortcut can fail
+POL_SetupWindow_make_shortcut "$PREFIX" "$PROGRAMFILES/GOG.com/Outcast/" "start.exe" "" "$SHORTCUT_NAME"
+cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Outcast/Outcast.ICO" "$REPERTOIRE/icones/32/$SHORTCUT_NAME"
 Set_WineVersion_Assign "$WORKING_WINE_VERSION" "$SHORTCUT_NAME"
 
-POL_SetupWindow_make_shortcut "$PREFIX" "/" "start" "" "Outcast user manual" "" "'Program Files/GOG.com/Outcast/manual.pdf'"
+POL_SetupWindow_make_shortcut "$PREFIX" "/" "start" "" "$SHORTCUT_DOC" "" "'$PROGRAMFILES/GOG.com/Outcast/manual.pdf'"
 
 
 POL_SetupWindow_Close
 
-cat <<EOF > $DIRECTORY/configurations/configurators/Outcast
+cat <<EOF > $REPERTOIRE/configurations/configurators/Outcast
 #!/bin/bash
 [ -z "\$PLAYONLINUX" ] && exit 0
 source "\$PLAYONLINUX/lib/sources"
-export WINEPREFIX="$DIRECTORY/wineprefix/$PREFIX"
+export WINEPREFIX="$REPERTOIRE/wineprefix/$PREFIX"
 export WINEDEBUG=""
-cd "\$WINEPREFIX/drive_c/Program Files/GOG.com/Outcast/" || exit 1
+
+case "\$POL_LANG" in
+    fr)
+        TITLE="Outcast (version Gog)"
+        LNG_CHOOSE_LANGUAGE="Choisissez le langage des voix et des sous-titres"
+        ;;
+    *)
+        TITLE="Outcast (GoG release)"
+        LNG_CHOOSE_LANGUAGE="Choose language for voices and subtitles"
+        ;;
+esac
+
+cd "\$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Outcast/" || exit 1
 
 CURRENT_LANG=English
 [ -f pol_configuration ] && source pol_configuration
@@ -123,7 +164,7 @@ CURRENT_LANG=English
 POL_SetupWindow_Init
 
 # Other language directories are incomplete (?)
-POL_SetupWindow_menu_list "Choose language" "Voices and subtitles" "English~French~German" "~" "\$CURRENT_LANG"
+POL_SetupWindow_menu_list "\$LNG_CHOOSE_LANGUAGE" "\$TITLE" "English~French~German" "~" "\$CURRENT_LANG"
 CURRENT_LANG="\$APP_ANSWER"
 case "\$CURRENT_LANG" in
     English)
